package inf2015.assurance;


public enum EnumCodeErreur
{
    DONNEES_INVALIDES,
    CODECONTRAT_ABSENT, CODECONTRAT_INVALIDE,
    NOCLIENT_ABSENT, NOCLIENT_INVALIDE,
    DOSSIER_ABSENT, DOSSIER_INVALIDE,
    MOIS_ABSENT, MOIS_INVALIDE,
    NOSOIN_INVALIDE, NOSOIN_INCONNU, NOSOIN_NONCOUVERT, NOSOIN_ABSENT,
    DATE_ABSENT, DATE_FORMATINVALIDE, DATE_MAUVAISMOIS,
    MONTANT_ABSENT, MONTANT_SIGNE_DOLLAR, MONTANT_FORMAT_INVALIDE, MONTANT_NEGATIF,
    POURCENTAGE_ABSENT, POURCENTAGE_INVALIDE, MAXIMUM_INVALIDE,
    CODEBENEFICIAIRE_INVALIDE,
    ARGENT_MONTANT_HORSBORNES,ERREUR_ARGENT,
    ERREUR_PARSEUR, FICHIERENTRANT_STRUCTUREINTERNEINADEQUATE,
    ERREUR_LECTURE_FICHIER, FICHIER_INTROUVABLE,
    INTERVALLES_COLLISION,
    ERREUR_INCONNUE
}
