
package reclamationsassurance;


public enum EnumErreurLecture {
    CONTRAT_ABSENT, CONTRAT_INVALIDE, NOCLIENT_ABSENT, NOCLIENT_INVALIDE,
    NOSOIN_ABSENT, NOSOIN_INVALIDE, DATE_ABSENT, DATE_FORMAT_INVALIDE, DATE_MAUVAISMOIS,
    MONTANT_ABSENT, MONTANT_SIGNEDEPIASSE, MONTANT_FORMATINVALIDE, CODESOIN_INEXISTANT
}
