
public enum EnumErreurLecture
{
    CODESOIN_INEXISTANT,
    CONTRAT_ABSENT, CONTRAT_INVALIDE,
    NOCLIENT_ABSENT, NOCLIENT_INVALIDE,
    DOSSIER_ABSENT, DOSSIER_INVALIDE,
    MOIS_ABSENT, MOIS_INVALIDE,
    NOSOIN_ABSENT, NOSOIN_INVALIDE,CODESOIN_INCONNU,
    DATE_ABSENT, DATE_FORMAT_INVALIDE, DATE_MAUVAISMOIS,
    MONTANT_ABSENT, MONTANT_SIGNEDEPIASSE, MONTANT_FORMATINVALIDE, MONTANT_NEGATIF,
    POURCENTAGE_ABSENT, POURCENTAGE_INVALIDE, MAXIMUM_INVALIDE
    
}
